"""One-shot: render the LangGraph agent as Mermaid into docs/agent_graph.md.

Usage (from repo root):
    python scripts/render_graph.py

This builds the graph structure only — it does NOT call any LLM — so it is
safe to run in CI or offline. The dependencies injected into
`build_agent_graph` are deliberate no-ops because we only need the graph's
topology, not its runtime behaviour.
"""

from __future__ import annotations

import os
import sys


def _ensure_repo_on_path() -> str:
    """Make `src.*` importable when this script is invoked from anywhere."""
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    if root not in sys.path:
        sys.path.insert(0, root)
    return root


def _noop_planner(_user_prompt, _cached_headlines, _history):
    return []


def _noop_dispatch(_name, _args, _original_prompt):
    return ""


def _noop_verify(_npi):
    return True


def main() -> int:
    root = _ensure_repo_on_path()

    try:
        from src.agent_graph import build_agent_graph
    except ImportError as e:
        print(f"ERROR: Could not import src.agent_graph ({e}).")
        print("Install deps first: pip install -r requirements.txt")
        return 1

    graph = build_agent_graph(
        _noop_planner,
        _noop_dispatch,
        _noop_verify,
        groq_api_key="",
    )

    try:
        mermaid = graph.get_graph().draw_mermaid()
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: draw_mermaid() failed: {e}")
        return 1

    docs_dir = os.path.join(root, "docs")
    os.makedirs(docs_dir, exist_ok=True)
    out_path = os.path.join(docs_dir, "agent_graph.md")

    content = (
        "# Agent Graph\n\n"
        "Auto-generated by `scripts/render_graph.py`. Do not edit by hand.\n\n"
        "This is the compiled LangGraph agent used when `USE_LANGGRAPH=true`\n"
        "is set in `.streamlit/secrets.toml`. See `src/agent_graph.py` for\n"
        "node implementations and `README.md` for the overall routing stack.\n\n"
        "## Node responsibilities\n\n"
        "| Node | Purpose |\n"
        "|---|---|\n"
        "| `plan` | Call the Groq tool-calling planner (`src/planner.py`) and produce an ordered list of tool calls. |\n"
        "| `execute` | Dispatch each tool call to the corresponding `_answer_*` handler in `streamlit_app.py`. |\n"
        "| `grounding_check` | Extract any 10-digit NPI from the draft outputs and verify it exists in the targeting dataset. Flags hallucinations. |\n"
        "| `reflect` | LLM-as-judge: if grounding failed OR a sub-question is missing, route back to `plan` for one retry. |\n"
        "| `finalize` | Stitch outputs into the final markdown, appending a grounding warning if a hallucination remained after retries. |\n\n"
        "## Diagram\n\n"
        "```mermaid\n"
        f"{mermaid.rstrip()}\n"
        "```\n"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {out_path} ({len(content)} bytes).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
